### ISSUE TITLE
How should workflow reckon with nested/related concerns (AKA complex objects)?

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/curation_concerns#1022]
If a concern is deposited via a workflow that requires review, and that concern has members (FileSets and/or works/curation concerns) or is a member of other concerns being deposited, how should the workflow treat all of the repository objects?

Should the states of all concerns be set together, _i.e._, all should be marked as suppressed, and later unsuppressed? (FileSets do not currently have states.)

Should state updates cascade up and down the graph of deposited objects?

If workflows are type-based, and the graph contains multiple work types, which workflow is selected? (Proposal: if the deposited thing is going into an admin set, just use the admin set's workflow.)

**Comment by jcoyne** [comment]
From my discussion with @tpendragon Plum does workflow on each discoverable object.  In a sammelband, each contained volume and the sammelband itself each goes through workflow independently.   FileSets do not have a workflow.
