### ISSUE TITLE
Implementing Workflow Action Callback Service Validation

### ISSUE THREAD

**Issue by jeremyf** [projecthydra/curation_concerns#1024]
With the addition of [CurationConcerns::Workflow::ActionTakenService](https://github.com/projecthydra/curation_concerns/blob/d797e6ad735430392a7d744c6304ded9f797e8bf/app/services/curation_concerns/workflow/action_taken_service.rb), implementors will make callback functions.

These functions should adhere to an expected interface. To provide guidance on updating installations, a spec helper (e.g. "it is expected to conform to the Workflow Action Callback Service interface) should be created.

See #1023

**Comment by mjgiarlo** [comment]
@jcoyne @jeremyf Should we pull this over to Hyrax, or meh?

**Comment by jeremyf** [comment]
@mjgiarlo I think this is something to move to Hyrax

**Comment by mjgiarlo** [comment]
@jeremyf OK, will do.

**Comment by mjgiarlo** [comment]
Moved to Hyrax: https://github.com/projecthydra-labs/hyrax/issues/240 Closing.
