### ISSUE TITLE
Create a debug view for an object's Workflow

### ISSUE THREAD

**Issue by jeremyf** [projecthydra/curation_concerns#1026]
In Sipity we have a debug page that allows users to see the state of the Sipity workflow:
- An object's Sipity::Workflow
- An object's Sipity::WorkflowState
- The list of Sipity::Roles that are assigned to the object, and how agents are associated with those roles (i.e. at the Workflow level or the Sipity::Entity level)

Example https://github.com/ndlib/sipity/blob/master/artifacts/for-sufia/sipity-ETD-Debug-page.png

**Comment by randalldfloyd** [comment]
The screen capture above was generated from 'debug' presenters and actors and a Curly template.  The best way to navigate all of the working pieces is to view the initial commit introducing debug to Sipity: https://github.com/ndlib/sipity/commit/cfe6204d0bffe260aa66cfefbf66087dbc0eeaf9

**Comment by mjgiarlo** [comment]
Is this related to #1030 in any way, @jeremyf?
