### ISSUE TITLE
add a "no state change" radio

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#1027]
This allows a user to leave a comment without changing the state.
- [x] Update [CurationConcerns::Workflow::WorkflowSchema](https://github.com/projecthydra/curation_concerns/blob/4760ee0d7019059702a1c9413bdf28a599ff41b7/app/services/curation_concerns/workflow/workflow_schema.rb#L13) (`required(:transition_to)` to be `optional(:transition_to)`)
- [x] Update [CurationConcerns::Forms:: WorkflowActionForm](https://github.com/projecthydra/curation_concerns/blob/4760ee0d7019059702a1c9413bdf28a599ff41b7/app/forms/curation_concerns/forms/workflow_action_form.rb#L55 to conditionally update the workflow state of an object.
- [ ] Update initial workflow to include "No State Change" radio button; This would be done by defining the "no_state_change" action that is available from each state for the given roles that should have access in [workflow.json.erb](https://github.com/projecthydra/curation_concerns/blob/workflow/lib/generators/curation_concerns/work/templates/workflow.json.erb) but not including the `transition_to` link.
  - See [CurationConcerns::Workflow::WorkflowSchema](https://github.com/projecthydra/curation_concerns/blob/workflow/app/services/curation_concerns/workflow/workflow_schema.rb#L19-L24) for guidance concerning schema definition.

**Comment by mjgiarlo** [comment]
Inclined to take this up again, @jeremyf ?
