### ISSUE TITLE
Allow workflow states to suppress visibility

### ISSUE THREAD

**Issue by elrayle** [projecthydra/curation_concerns#1028]
### Descriptive summary

Version: 0.7.x

Configuration for workflow states should allow suppression of objects in that state.

### Expected behavior

If a workflow configures that objects in state A are suppressed, then any objects in that state will not be visible to public users even if `object.visiblity == PUBLIC`.  For logged in users, visibility will be dependent on their role in the workflow.

### New Work

* update workflow configuration to be allow states to set `suppressed=TRUE|FALSE` (exact syntax TBD)
* update solr indexing to add suppressed flag  (This is a solr supported feature, but I couldn't find the doc with a quick search.)
* update abilities for roles that includes a check of the suppressed flag
**  public users never see any object that are suppressed
**  admins can see all objects even if suppressed
* UI badge that indicates the object is suppressed that shows to right of visibility badge on show pages and in lists

### Related work

TBD

**Comment by jcoyne** [comment]
Done via #1049
