### ISSUE TITLE
Simpler default workflow

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#1031]
One step of mediation, with the capability to return it to the initial state.

**Comment by vantuyls** [comment]
likely duplicate of #1035 - @jcoyne @mjgiarlo can we close this?

**Comment by mjgiarlo** [comment]
@vantuyls As I read it, #1031 was building on #1035, but I ultimately defer to @jcoyne or @jeremyf as to whether or this ticket is functionally identical to #1035.

**Comment by jeremyf** [comment]
@mjgiarlo I believe these are different.

**Comment by jcoyne** [comment]
Agreed, they were different. However, it's unclear how we deliver both #1031 and #1035. Which workflow should we generate?

**Comment by mjgiarlo** [comment]
We have this workflow in Sufia and Hyrax now. Closing.
