### ISSUE TITLE
Certain states should be excluded from the list of things to take action on

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#1034]
For example, you may have the ability to "flag" everything, but we don't want that ability on the list. Potentially put this as a field in the config (e.g. `shows_on_admin_page: false`)

**Comment by mjgiarlo** [comment]
@jcoyne is this actionable now, or should we close it?

**Comment by jcoyne** [comment]
I believe this is actionable now

**Comment by mjgiarlo** [comment]
@jcoyne OK. Moved to Hyrax. https://github.com/projecthydra-labs/hyrax/issues/232
