### ISSUE TITLE
Null workflow stategy = current New Work without workflow

### ISSUE THREAD

**Issue by elrayle** [projecthydra/curation_concerns#1035]
### Descriptive summary

Define workflow that can be used as default for current process used to create a New Work. 
### Expected behavior

When on the New Work UI, user can upload, set metadata, set relationships, and save without having to transition through states.
### New Work
- define a one state workflow that allows user to everything

**Comment by scholarworks** [comment]
Since workflows aren't picked up unless manually loaded into the DB, no workflow is the default behavior. Do we need this ticket?

**Comment by jcoyne** [comment]
It would be better if we could *always* depend on a workflow and never had to do a null check.

**Comment by mjgiarlo** [comment]
@scholarworks @jcoyne Should this PR include then some way to automatically load the default workflow, e.g., when a curation concern is created?

**Comment by scholarworks** [comment]
@jcoyne @mjgiarlo - confirmed that a null workflow (i.e., has the work type name but zero actions) throws an error on load. I do have a very basic single step ("submitting") workflow outlined that may be sufficient.

https://github.com/scholarworks/curation_concerns/blob/workflow/lib/generators/curation_concerns/work/templates/workflow.json.erb

If this looks OK, I'll do a PR. Otherwise, I can keep cleaning it up.

**Comment by mjgiarlo** [comment]
@jcoyne @scholarworks Fair warning: I care more about names than I should, sometimes. ;)

My only questions about your json are related to naming. The names that are conventionally used for states in Sipity are words or phrases that can complete the sentence "The work is ____." So how about something like "new" as the initial state and "deposited" as the final state? If those are the states, I might also rename the "complete" action to "deposit" it to align with the state names, and rename the role to "depositing". So like:

```json
{
  "work_types": [
    {
      "name": "<%= file_name %>",
        "actions": [{
          "name": "deposit",
          "from_states": [{"names": ["new"], "roles": ["depositing"]}],
          "transition_to": "deposited",
          "notifications": [
             {
               "notification_type": "email",
               "name": "confirmation_of_submitted_to_ulra_committee",
               "to": ["creating_user"],
               "cc": ["advising"]
             }
           ],
           "methods": [
             "CurationConcerns::Workflow::ActivateObject"
           ]
        }]
    }
  ]
}
```

**Comment by mjgiarlo** [comment]
@jcoyne @scholarworks My other question (more for @jcoyne and @vantuyls) is whether we should keep the `work_types` jazz in there given other discussions about moving away from work types as a way to assign and manage workflows.

Thanks, @scholarworks!

**Comment by jcoyne** [comment]
Yeah, we should remove `work_types` and we should add a `label` and `description` field.  As far as what you call the states, I DGAF, @jeremyf seemed to have strong feelings though.

**Comment by mjgiarlo** [comment]
I suspect my suggested names are @jeremyf-friendly, but I'll let him be the judge! :+1: to your suggested changes, @jcoyne.

**Comment by scholarworks** [comment]
@mjgiarlo I have no strong feelings on names, so I totally welcome these.

@jcoyne - at what level will the `label` and `description` field go?  Same as `name`?

**Comment by jcoyne** [comment]
@scholarworks yes, at top level of the workflow.

**Comment by scholarworks** [comment]
Something like this:

`{
  "label": "Default Workflow",
  "description": "A single submission step, default workflow",
  "actions": [{
    "name": "deposit",
    "from_states": [{"names": ["new"], "roles": ["depositing"]}],
    "transition_to": "deposited",
    "notifications": [{
      "notification_type": "email",
      "name": "confirmation_of_submitted_to_ulra_committee",
      "to": ["creating_user"],
      "cc": ["advising"]
    }],
    "methods": [
      "CurationConcerns::Workflow::ActivateObject"
    ]
  }]
}
`

**Comment by jcoyne** [comment]
@scholarworks We still need a `"name"` at the top level, and I think we should keep the `  "work_types"` too, but change it to something like `"workflows"`

**Comment by mjgiarlo** [comment]
```json
{
  "workflows": [
    {
      "name": "default",
      "label": "Default Workflow",
      "description": "A single submission step, default workflow",
      "actions": [{
        "name": "deposit",
        "from_states": [{"names": ["new"], "roles": ["depositing"]}],
        "transition_to": "deposited",
        "methods": [
          "CurationConcerns::Workflow::ActivateObject"
        ]
      }]
    }
  ]
}
```

**Comment by jcoyne** [comment]
@mjgiarlo shoudn't the `from_states` for deposit be `[]`?

**Comment by mjgiarlo** [comment]
@jcoyne yep. just fixed that, in fact, after I ran into errors. ;)
