### ISSUE TITLE
UI for managing groups and roles.

### ISSUE THREAD

**Issue by elrayle** [projecthydra/curation_concerns#1037]
### Descriptive summary

UI for managing groups and roles.  Allow groups|users to be assigned a role.
### Expected behavior

There is a start on mockups for this, but they need work.  This is only a starting point.  Hopefully there will be more input from the UI community on how to convey this complex set of interactions.

Mockup for Manage Roles:  https://wiki.duraspace.org/x/hYaoB
Mockup for Manage Groups:  https://wiki.duraspace.org/x/SIaoB
### Related Work

Workflow configuration effort.

**Comment by vantuyls** [comment]
I think we're focusing on Roles right now and pushing Groups off into future.

**Comment by jcoyne** [comment]
And counter to what the mockups show, workflow roles have nothing to do with admin sets.
