### ISSUE TITLE
Workflow i18n translations missing if work type is not called 'Generic Work'

### ISSUE THREAD

**Issue by randalldfloyd** [projecthydra/curation_concerns#1043]
The new workflow i18n translations are keyed to curation_concerns.workflow.generic_work, but if you use the CC work type generator and call your new type something arbitrary, it will produce translation missing errors.  Either the translations should not use the work type name, or the generator will need to take care of adding the translations when new work types are created.

**Comment by jeremyf** [comment]
One solution is that our translations should have a "suitable" default. In this case, I would assume translating `Sipity::Action#name` should fall back to `Sipity::Action#name.titlelize`.

**Comment by jeremyf** [comment]
Closing with @bb3013c701afc518be071d09db529ca7b9ad8e79.

If this does not resolve the problem, please re-open with further details (i.e. call stack)
