### ISSUE TITLE
"Download this File" fails within existing browser windows

### ISSUE THREAD

**Issue by dunn** [projecthydra/curation_concerns#1050]
Affects at least 0.12.0 through 5ed966284a2123a50e40414e32f1ab64a7738d5b.

cc @val99erie 

### Steps to reproduce the behavior

1. `rake engine_cart:generate`
2. `cd .internal_test_app && bundle exec fcrepo_wrapper`
3. `cd .internal_test_app && bundle exec solr_wrapper`
4. `cd .internal_test_app && bin/rails s -b 0.0.0.0`
5. Sign up, create a new generic work, add a file to it.
6. Go to the FileSet show page (`http://localhost:3000/concern/file_sets/<id>`), and click "Download this File"

### Expected behavior

The PDF viewer displays the file, or the file is downloaded if there's no in-browser PDF viewer.

### Actual behavior

The browser attempts to render the PDF as text:
![screen shot 2016-10-10 at 10 29 05 am](https://cloud.githubusercontent.com/assets/985416/19245154/72255766-8ed4-11e6-85ca-057f928b1118.png)

When the file is an MP3, the browser freezes.

Opening the link in a new tab or window results in the correct behavior, however.

**Comment by no-reply** [comment]
I'm able to recreate this in any browser by removing `target="_new"` from the button link. Note that `_new` is not a [browsing context keyword in HTML5](http://w3c.github.io/html/browsers.html#browsing-context-names), and the spec recommends ignoring non-keywords that begin with '_'.

When opening in the same browser window, I get `text/html` as the content type. I'm looking into why.

In the meanwhile: It looks to me like @dunn's browser is ignoring `_new`. A proposed workaround would be to switch to `_blank`, which is the appropriate keyword.
