### ISSUE TITLE
Consider removing notifiable contexts from Sipity::WorkflowState

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#1054]
I think the notifiable_contexts in Sipity::WorkflowAction ought to be sufficient.

**Comment by jcoyne** [comment]
@jeremyf what do you think of this proposal?

**Comment by jeremyf** [comment]
The plan would be to replace those with functions as part of the callback? I can get behind that. It would move the configuration of emails out of the database and into a function.

**Comment by jcoyne** [comment]
@jeremyf I don't think I made myself clear.  Presently it allows WorkflowState and WorkflowAction to be notifiable contexts. I'm positing that we don't need notifiable contexts for both states and actions.  I think that notifications should happen only on WorkflowActions.

**Comment by jcoyne** [comment]
@jeremyf ping?

**Comment by mjgiarlo** [comment]
:arrow_up: @jeremyf comments?

**Comment by jeremyf** [comment]
Yes. Notifications need only happen for actions.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
OK, I'll move this to Hyrax. Thanks!

**Comment by mjgiarlo** [comment]
Moved to Hyrax: https://github.com/projecthydra-labs/hyrax/issues/231 Closing.
