### ISSUE TITLE
[bug] WorkflowActionService can cause sipity entity and work to become out of sync

### ISSUE THREAD

**Issue by revgum** [projecthydra/curation_concerns#1096]
A WorkflowAction, such as ActivateObject or DeactivateObject cause cause an update to the sipity entity (changing state: https://github.com/projecthydra/curation_concerns/blob/1be404f895c71292ed2614d26022c36b964a9b3b/app/services/curation_concerns/workflow/activate_object.rb#L5) which persists to SOLR. 

`subject.work` becomes out of sync and has previously set state causing SOLR to change during the `update_index` call at: https://github.com/projecthydra/curation_concerns/blob/1be404f895c71292ed2614d26022c36b964a9b3b/app/services/curation_concerns/workflow/workflow_action_service.rb#L21

`subject.work.reload` refreshes with changes that could have been made by the WorkflowAction

**Comment by jcoyne** [comment]
I think the problem you see here is that the changes are not getting persisted to fedora. I suspect it's actually a `work.save` that's missing.

**Comment by jcoyne** [comment]
Actually, it seems like save *is* being called here: https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/workflow/action_taken_service.rb#L30

**Comment by jcoyne** [comment]
I see what you're saying:
```
[30, 39] in /Users/jcoyne/workspace/curation_concerns/app/services/curation_concerns/workflow/action_taken_service.rb
   30:           Rails.logger.debug("Result of #{method.service_name} is #{status}")
   31:           status
   32:         end
   33:
   34:         byebug
=> 35:         return entity.proxy_for.save if success
   36:         Rails.logger.error "Not all workflow methods were successful, so not saving (#{entity.id})"
   37:         false
   38:       end
   39:
(byebug) entity.proxy_for.object_id
70341471503920
(byebug) n

[16, 25] in /Users/jcoyne/workspace/curation_concerns/app/services/curation_concerns/workflow/workflow_action_service.rb
   16:       def run
   17:         update_sipity_workflow_state
   18:         comment = create_sipity_comment
   19:         handle_sipity_notifications(comment: comment)
   20:         handle_additional_sipity_workflow_action_processing(comment: comment)
=> 21:         subject.work.update_index # So that the new actions and state are written into solr.
   22:       end
   23:
   24:       protected
   25:
(byebug) subject.work.object_id
70341466864260
```
