### ISSUE TITLE
rescue_from should use a named method to allow override

### ISSUE THREAD

**Issue by atz** [projecthydra/curation_concerns#1104]
https://github.com/projecthydra/curation_concerns/blob/v1.7.0.beta1/app/controllers/concerns/curation_concerns/collections_controller_behavior.rb#L18-L27

```ruby
      rescue_from Hydra::AccessDenied, CanCan::AccessDenied do |exception|
        if exception.action == :edit
          redirect_to(url_for(action: 'show'), alert: 'You do not have sufficient privileges to edit this document')
        elsif current_user && current_user.persisted?
          redirect_to root_url, alert: exception.message
        else
          session['user_return_to'] = request.url
          redirect_to new_user_session_url, alert: exception.message
        end
      end
```

The `do` block should be split off into a named method that a downstream consumer can easily override.  See: https://github.com/projecthydra/hydra-head/blob/7a911e54a7cc0c49ca0e9cc8da1c6d47f9a467bb/hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb#L13

**Comment by jcoyne** [comment]
👍
