### ISSUE TITLE
Administrator abilities

### ISSUE THREAD

**Issue by awead** [projecthydra/curation_concerns#1118]
### Descriptive summary

Administrators aren't able to see files attached to works, view thumbnails, or download their content.

At Penn State we fixed this my making changes to DownloadsController and Ability.

https://github.com/psu-stewardship/scholarsphere/commit/fe3cd199ec7bd912e815cdda9df0d793f1e667e3

I'm marking the issue here, but I'm not sure if the patch should be the same or go in this repo.

**Comment by jcoyne** [comment]
I'd suggest fixing the download issue by doing this in `Ability`:

```ruby
can :download, :all if admin?
```

**Comment by awead** [comment]
Good idea. Doesn't work right off the bat, so there needs to be some tweaking in CanCanCan maybe.
