### ISSUE TITLE
CI fails on Ruby 2.3.3

### ISSUE THREAD

**Issue by no-reply** [projecthydra/curation_concerns#1124]
### Descriptive summary

On current master, `rake ci` fails when generating the test app with `Bundler could not find compatible versions for gem "rspec-core"` and `Bundler could not find compatible versions for gem "nokogiri"`.

### Expected behavior

EngineCart succeeds at building the test app and tests run normally.

### Actual behavior

EngineCart reports `Done generating test app`, and CI continues, raising an error on `uninitialized constant FileSet`.

### Steps to reproduce the behavior

```bash
git clone https://github.com/projecthydra/curation_concerns.git
cd curation_concerns

# rbenv local 2.3.3
ruby --version       # ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
bundle --version   # Bundler version 1.13.7

bundle install
bundle exec rake ci
```

Output is given in [this gist](https://gist.github.com/no-reply/b6e9c2be7cb09526c5f2662fe522fa75). EngineCart fails silently, and the CI task attempts to run the specs, leading to the misleading `NameError`. The reported dependency conflicts don't seem to conflict, and I wasn't able to find a version of bundler that worked in the 1.12.x or 1.13.x branches.

I sometimes get a different [error message](https://gist.github.com/no-reply/0bc6a41503376a849f28738c332c5a07) having to do with Solr. I can recover from this error by doing `rm -rf /tmp/solr-*`. The error reports that details will be in `/tmp/solr-6.3.0/logs` which does not exist. This may need to be raised in a separate ticket.

### Related work

EngineCart's silent failure has been reported at https://github.com/cbeer/engine_cart/issues/66. A patch is proposed there. Using the proposed branch of EngineCart allows CI to continue normally by running `bundle update` after the initial `bundle install` fails.

It's not clear to me where the underlying error originates and whether there is a CurationConcerns specific issue that needs to be addressed, but felt it was best to report this in detail.

**Comment by jcoyne** [comment]
@no-reply Can this be closed now?

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra/curation_concerns/pull/1127
