### ISSUE TITLE
Upstream changes appears to have broken the build

### ISSUE THREAD

**Issue by jeremyf** [projecthydra/curation_concerns#1142]
To duplicate the error:

* Fetch all updates to master
* Run `bundle update`
* Run `$ rake`

Example of builds blocked:

* #1140
* #1141

**Comment by hortongn** [comment]
Looks like hydra-head 10.4.0 broke the test.

spec/services/curation_concerns/workflow/permission_query_spec.rb:171 passes on hydra-head 10.3.4.  After the update to 10.4.0 it fails.

The very first commit AFTER 10.3.4 seems to break that test:
Remove registered pseudo-group from RoleMapper
https://github.com/projecthydra/hydra-head/commit/a606ea073927d4e184e5d0472f571086e19794ea

@jeremyf @jcoyne

**Comment by jcoyne** [comment]
Ah. I've already fixed this in Hyrax. Should be an easy back port
