### ISSUE TITLE
WorkShowPresenter ordered_ids and file_set_ids return differing numbers

### ISSUE THREAD

**Issue by awead** [projecthydra/curation_concerns#1144]
### Descriptive summary

If I have a work with more than 10 files in it, I get into a situation where CompositePresenterFactory returns the default presenter, WorkShowPresenter, instead of a FileSetPresenter.

A composite presenter is built here:

https://github.com/projecthydra/curation_concerns/blob/master/app/presenters/curation_concerns/work_show_presenter.rb#L84

It uses the intersection of ordered_ids and file_set_ids, however, whereas the former will return all ordered ids, the latter only returns the default number according to the solr rows parameter which is usually 10.

This causes problems when building the representative presenter:

https://github.com/projecthydra/curation_concerns/blob/master/app/presenters/curation_concerns/work_show_presenter.rb#L62

If your representative id is not in the intersection of ordered_ids and file_set_ids, which if your work has a lot of files this may very well be the case, a WorkShowPresenter is returned instead of a FileSetPresenter. This causes an infinite loop at line 56.

The quick fix would just be to add a large rows parameter to the solr query for file_set_ids.

**Comment by jcoyne** [comment]
@awead is this same as this? https://github.com/projecthydra/curation_concerns/commit/1f419480fad3c80bdc4b971a622515c947f6eeba

**Comment by awead** [comment]
@jcoyne ah that's it. I forgot we're pinned to a different version. I'll close this, but leave the hyrax issue open since it has the older method.
