### ISSUE TITLE
Type mismatch in PermissionQuery

### ISSUE THREAD

**Issue by escowles** [projecthydra/curation_concerns#1152]
When I try to transition an object in a Sipity workflow, I get an error in PermissionQuery.scope_users_for_entity_and_roles: "ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  operator does not exist: integer = character varying", because there is a mismatch between the user.id column (integer) and the subquery (which produces varchars).  Note: this error doesn't happen with SQLite, but does happen with PostgreSQL.

The query is being executed here: https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/workflow/permission_query.rb#L267

We should be able to explicitly cast the user.id value to a varchar.

**Comment by jcoyne** [comment]
See https://github.com/projecthydra-labs/hyrax/commit/094c540124cb501f35a71e312954acbbdb13179c
