### ISSUE TITLE
Re-enable single-use links in the UI

### ISSUE THREAD

**Issue by tampakis** [projecthydra/curation_concerns#278]
Although all of the single-use link functionality is in CurationConcerns, there isn't a way actually generate one from the interface. Single-use links are no longer exposed in the UI.

1. Single-use links will be exposed in the UI for `FileSets` only (not for e.g., `GenericWorks` or other curation concerns).
1. Only one single-use link will be generated for each `FileSet`, allowing download access to the `original_file` within the `FileSet`.
1. Clicking the single-use link button for a `FileSet` should not redirect to a new view, but rather it should pop up a (Bootstrap) modal showing the single-use link, highlighted, with a GitHub-like "copy me" button beside it. Consider using https://clipboardjs.com/ for this.

You may want to review and adapt/re-use the following bits of implementation from Sufia:

* https://github.com/projecthydra/sufia/blob/af6a75095047ae3cd8aeffd145713305aa63f041/app/assets/javascripts/sufia/single_use_link.js
* https://github.com/projecthydra/sufia/blob/af6a75095047ae3cd8aeffd145713305aa63f041/app/assets/javascripts/sufia.js#L39
* https://github.com/projecthydra/sufia/blob/af6a75095047ae3cd8aeffd145713305aa63f041/spec/javascripts/single_use_link_spec.js.coffee
* https://github.com/projecthydra/sufia/blob/af6a75095047ae3cd8aeffd145713305aa63f041/app/views/my/_action_menu.html.erb#L8-L11

This note may be useful or it may be outdated:

> Make sure the link renders if a title isn't set on the file. This [link](https://github.com/projecthydra-labs/curation_concerns/blob/39f7b89b43c8add7ea71547362663c69005931ba/app/views/curation_concerns/single_use_links/new_download.html.erb#L4) and this [link](https://github.com/projecthydra-labs/curation_concerns/blob/39f7b89b43c8add7ea71547362663c69005931ba/app/views/curation_concerns/single_use_links/new_show.html.erb#L4) don't render when the title attribute isn't set.

**Comment by awead** [comment]
@mjgiarlo I think implementing this would fix projecthydra/sufia#2368

**Comment by mjgiarlo** [comment]
:ok: @awead

**Comment by mjgiarlo** [comment]
@awead also, see the comments @hectorcorrea and I left on this ticket if you have questions about scope or direction: https://github.com/projecthydra/sufia/issues/1750#issuecomment-209565443

**Comment by awead** [comment]
Thanks, that's what I'm planning on doing. There's also the addition of show_links, which we'll to distinguish between in the UI.

**Comment by mjgiarlo** [comment]
Not sure I follow, @awead, but np! :athletic_shoe: with it.

**Comment by cam156** [comment]
@tampakis Is there a reason why you are limiting to a single single use link per file?
The link can only be used once, so if I want to share the file with 3 people the old implementation allowed for you to create one per person.  The new implementation would only allow sharing with one person at a time.

**Comment by awead** [comment]
I'm fine with multiple links per type, either show or download, but the UI should have the ability to delete links. Perhaps a table that lists each link with its expiration data, a button to copy it to the clipboard, and a ❌  to delete it?

**Comment by tampakis** [comment]
@cam156 I see. When I opened the ticket almost a year ago, I was unaware of the ability to share a file with multiple people. I just had noticed that the single-use link code was in Curation Code, but wasn't enabled in the UI.

Also, the sufia and CC codebase has changed quite a lot since this issue was opened. The links I pasted are out of date because they were pinned to the master branch. They should have been pinned to https://github.com/projecthydra/sufia/commit/af6a75095047ae3cd8aeffd145713305aa63f041 and https://github.com/projecthydra/curation_concerns/commit/39f7b89b43c8add7ea71547362663c69005931ba. I've updated the links to point to those commits (although I'm not sure how useful they are since the code has changed so much since then).

**Comment by mjgiarlo** [comment]
@awead :speech_balloon: 
> I'm fine with multiple links per type, either show or download, 

The current spec is calling only for download links for the `original_file` within a `FileSet`. I'm -0 on show links.

> but the UI should have the ability to delete links. Perhaps a table that lists each link with its expiration date, a button to copy it to the clipboard, and an :x: to delete it?

I wouldn't *object* to surfacing single-use tracking/management... but this goes beyond "re-enable" to "build some new features." I might encourage you to simply re-enable now (satisfying this ticket), and while Travis is :watch:, write up new ticket(s) for the new feature(s).?

**Comment by awead** [comment]
@mjgiarlo the problem lies in Sufia's ticket https://github.com/projecthydra/sufia/issues/2368. The ideal solution would be to break apart the link creation with the copying of the link to the clipboard. Also, Sufia's current behavior allows the user to create multiple links without really being able to manage them. I believe the proposed changes here would fix all of that.

**Comment by mjgiarlo** [comment]
@awead if you're inclined to do all of this work in one fell swoop, I would not discourage you!

**Comment by awead** [comment]
😈
