### ISSUE TITLE
rspec:install generator not getting run

### ISSUE THREAD

**Issue by afred** [projecthydra/curation_concerns#337]
**To reproduce:**
  1. create a new rails app
  1. install `curation_concerns` per README
  1. create a work type, e.g. `rails g curation_concerns:work MyThing`
  1. try to run specs with `rspec spec/models/my_thing_spec.rb`

After doing this, I get the error: `'require': cannot load such file -- rails_helper (LoadError)`.

**workaround:** run `rails g rspec:install`

But if `curation_concerns` is generating code that requires rspec to have been installed, shouldn't the `curation_concerns:install` generator ensure that?

**Comment by cbeer** [comment]
I don't think it's our place to run the `rspec:install` generator for you. We're not explicitly requiring rspec, and we're checking if the application has `rspec` before generating specs into the application.

**Comment by afred** [comment]
Interesting. I'm not sure how specs were generated when I didn't have rspec installed. M'oh well.
