### ISSUE TITLE
Extract subclass LinkAttributeRenderer from AttributeRenderer

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#406]
This subclass will render the value if there is a link.

Split this class into two classes: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/renderers/curation_concerns/attribute_renderer.rb		

The base class for rendering the attribute as text. Then make a subclass that rendres the attribute as a link.	The subclass can just override: `li_value()`. This will be useful with sufia where they have link_to_search and link_to_facet.  Once this is done, those could just be subclasses.

**Comment by njaffer** [comment]
@jcoyne, I can work on this if you can provide me some more info.
