### ISSUE TITLE
Edit Work that has inactive rights.

### ISSUE THREAD

**Issue by grosscol** [projecthydra/curation_concerns#775]
### Descriptive summary
Editing a work that has inactive rights will force a user to either cancel the edits or select a rights statement from the list of active rights.

CC HEAD.

### Expected behavior
Edit the metadata of a work without having to choose a new rights statement.

### Actual behavior
Editting the metadata requires selection of a currently active rights statement.  In the case of legacy Works, this will require the user to change the rights from what was originally granted for the Work.

### Steps to reproduce the behavior

1. Create Work
1. Set rights selection to an rights statement with active: false. (via rails console)
1. Edit the Work

### Related work
This is a consequence of #767.  The contributor neglected to bring this issue to light or have a solution for it at the time of the PR.  Not going to name any names, but it was me.

**Comment by jenlindner** [comment]
Might not be testing this well, but I can't reproduce the error. I'm looking at this in a test app inside Sufia, after modifying the rights.yml in my curation_concerns gem to have an inactive id. Creating a work with the inactive id is fine (is that a sign that my setup isn't using the .yml file?), editing it with the inactive id is fine, creating one with an active id and changing it to the inactive one in the console is fine - nothing prevents a save.

Any thoughts?

**Comment by jcoyne** [comment]
Did you restart your rails server after changing rights.yml?  AFAIK that file is only parsed once during server startup.

**Comment by jenlindner** [comment]
Yes, I did. Changing the right to inactive in the console of the test app also didn't work though, something is either not right in my setup or it got fixed in the last week. Is there a way to reproduce this other than things I'm doing, @grosscol?

**Comment by jenlindner** [comment]
Nvm, the rights.yml needs be changed in the test app, not the gem.

**Comment by grosscol** [comment]
You should also be able to reproduce this in Curation Concern's internal test app.  There is a rights selection method in the form for New Generic Work
