### ISSUE TITLE
Add a configuration for job to queue

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#790]

**Comment by mjgiarlo** [comment]
@tpendragon Is this on your plate for this week, good sir? We're talking about the Sufia 7 timeline and this is blocking at the moment so it'd be good to know what your schedule looks like.

**Comment by tpendragon** [comment]
I think @escowles and you all convinced me that putting the configuration in another class is no more organized than configuring it in an initializer if you need it. It's only an issue if you want runtime configuration of priority, and I don't think that's a use case yet.

**Comment by tpendragon** [comment]
If you'd like, I'd be happy to switch all the jobs to a priority-type queue, though. I'd probably just put everything in 'low' though. ;)

**Comment by mjgiarlo** [comment]
Thanks, @tpendragon. FWIW, I don't think the HyBox team cares as much about runtime config of queue priority as we did when this issue was created.
