### ISSUE TITLE
Job concurrency

### ISSUE THREAD

**Issue by awead** [projecthydra/curation_concerns#795]
### Descriptive summary

Since an original file must be present before characterization can be done, and the current `CharacterizeJob` also calls `CreateDerivativesJob`, there's a concurrency problem.

Should we make all three jobs run successively with a large superjob?
1. IngestLocalFileJob/IngestFileJob
2. CharacterizeJob
3. CreateDerivativesJob

Or do we want to explore some kind of locking?

Note, this was brought up with #793 because it will expose the problem.

**Comment by awead** [comment]
ping @escowles @tpendragon

**Comment by jcoyne** [comment]
I'd say refactor the IngestFileJob to kick off the Characterize and CreateDerivatives once the file has been ingested. Then there is no race condition.

**Comment by mjgiarlo** [comment]
Will #793 expose the problem? I thought the superjob approach would be the problematic one. As long as IngestFileJob saves then calls CharacterizeJob, which saves and then calls CreateDerivativesJob... we should be OK, right?

**Comment by escowles** [comment]
👍  to having IngestFileJob kick of the Characterize and Derivatives jobs.  That's what we're doing in Plum, and we put the Characterize/Derivatives jobs on a lower priority queue to get files ingested into Fedora more quickly.

**Comment by tpendragon** [comment]
Yes, @jcoyne, that fixes the race condition. It makes derivatives kick off slower (delayed by however long it takes to get the object in), but I think that's it.

**Comment by jcoyne** [comment]
Yea. It's a bummer. I blame all the modeling zealots. ;)

**Comment by awead** [comment]
@mjgiarlo if you merge #793, it will expose the problem because there's no check (currently) to ensure `:original_file` is present.

**Comment by mjgiarlo** [comment]
@awead sorry, you're right. What I was referring to the alternative impl I suggested on #793, which is to invoke CharacterizeJob from IngestFileJob.

**Comment by awead** [comment]
👍 to the 'kickoff' 🏈  approach. Should that apply to both IngestLocalFileJob and IngestFileJob?

**Comment by jcoyne** [comment]
Another possibility is to put that characterization info in a staging location, and ingest it when you ingest the object.

**Comment by awead** [comment]
hmm. That's intriguing. We'd need to modify hydra-works to accept the xml metadata directly. Not a big deal, though.

**Comment by mjgiarlo** [comment]
What's the downside of leaving things as they are now and moving invocation of the CharacterizeJob to the IngestFileJob? That's the expedient approach, anyway.

**Comment by awead** [comment]
@mjgiarlo yes, expedient for now. But, characterize jobs would have to reload the binary from Fedora. @jcoyne's suggestion has the benefit of avoiding that.

**Comment by mjgiarlo** [comment]
Does the CreateDerivativesJob depend upon the CharacterizeJob firing off first (like, knowing the mime type)?

**Comment by awead** [comment]
@mjgiarlo yes, at least, according to the code in CC: the derivatives job is invoked by the characterize job. Mime type shouldn't be a problem because the file set will have been saved after the characterization job is run and the metadata would be available to the file set.

**Comment by jcoyne** [comment]
@awead why would characterize need to reload the binary from fedora?  It's still in the staging area. It should just continue to use that.

**Comment by awead** [comment]
@jcoyne https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/services/characterization_service.rb#L9

We'd pass the staging file as the second parameter.
