### ISSUE TITLE
Remove FileManager List/Grid Toggle Button?

### ISSUE THREAD

**Issue by tpendragon** [projecthydra/curation_concerns#807]
Right now there's a button which switches between a list and a grid display for the File Manager. We're finding that the list view is pretty useless though - any complaints if I just remove it?

**Comment by jcoyne** [comment]
👍  to removing. I don't know that anyone else is using file manager besides you.  @mark-dce ?

**Comment by mark-dce** [comment]
I'm ok with removing it for now (and potentially adding back when we have better use cases and related acceptance criteria) - does that seem OK?

**Comment by tpendragon** [comment]
:+1: Thanks @mark-dce
