### ISSUE TITLE
Update Visibility help text

### ISSUE THREAD

**Issue by justcolin** [projecthydra/curation_concerns#824]
### Descriptive summary

The recent revision to help text in CC visibly exposed the fact that the help text for the Visibility field is quite long. Not only is it cluttering the page, help text that long generally isn't very helpful for users. I talked with @heidisb and she came up with the following help text.

I also think the layout for the Embargo and Lease options could be cleaned up and will add that to the PR.

### Heidi's suggested update to the help text

> Who should be able to view or download this content and see the associated metadata? 
>  
> This is a blanket visibility setting. If you want to be able to selectively allow access, choose Private. 

### Heidi's suggested update to the labels

> **Open Access** - Everyone. Keep in mind this **may** be viewed as publishing and impact your ability to patent your work and/or publish your work in a journal. Check out [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/) for specific publishers' copyright policies. 
> 
> **Your Institution** - Only users who are logged in through your institution
> 
> **Private** - Only users and/or groups that have been given specific access in the "Share With" section.

### How it currently looks

<img width="481" alt="screen shot 2016-05-27 at 11 20 53 am" src="https://cloud.githubusercontent.com/assets/11234702/15612749/11c1754e-23fe-11e6-84a6-4f4041d35a94.png">

**Comment by justcolin** [comment]
@projecthydra/sufia-ui-ux-advisors, thoughts?

**Comment by heidisb** [comment]
In addition to the suggestions Colin shared, I also recommend having the order be...

Open Access
Your Institution
Private
Embargo
Lease

...so that everything has been defined when you get to Embargo and Lease. Further, those two words are so super jargony and I don't think they're even necessary in the context of this page, but I don't know if/how they appear elsewhere.

**Comment by newmanld** [comment]
+1 to @heidisb for both shorter descriptions and to order, so that Private is defined before it is referred to by Embargo and Lease.  

I would also be ok without the  'Keep in mind this may be viewed as publishing ...' warning and instead a briefer link to a longer, separate help page about Creator Rights (which can include a link to Sherpa/Romeo).  But that's a bigger policy question I suppose.

**Comment by simosacchi** [comment]
Three comments and (possibly) a bug:
- I agree with @heidisb that the help text is extremely long. On her suggested text though, I have the feeling that users might be pushed to set the access level to Private. I would just keep it short to the first sentence and make the individual choices speak for themselves.
- The text under Open Access is unnecessarily cautionary. Now, I might be biased by personal beliefs and how I conceive an IR, but I think having a more positive approach highlighting the benefits of OA  there would only benefit institutions using Sufia in its default config. 
- The "Embargo" and "Lease" options as @justcolin pointed out are a bit visually confusing given the approach of constructing a sentence out of multiple selection forms. What about having something like

> Visibility status: [form here]
> Until: [form here]
> Then: [form here]

(in three distinct lines)

Also attaching a screenshot: apparently the right column where the visibility status is, hides the main content area when you are on the File tab and resizing:
<img width="994" alt="screen shot 2016-05-27 at 12 26 52 pm" src="https://cloud.githubusercontent.com/assets/6808470/15614353/4f47460c-2406-11e6-85eb-a196173a1332.png">

**Comment by heidisb** [comment]
To your first point about pushing people toward Private, Simon, I tend to agree. I was trying to come up with an alternative to the original second paragraph about permissions being hierarchical. I do think the choices can speak for themselves.

Regarding the Open Access cautionary text, I purposely tried not to instill any change in meaning and that text was already there after Please Note (which I strike anytime I see it). Colin also asked that I try to keep it all on one page. I do not see a reason for us to reinvent the wheel and create a separate Creator/Author rights help page when there is tons of stuff already out in the world written by experts.

**Comment by simosacchi** [comment]
@heidisb +1 on everything you said in the previous comment.

**Comment by newmanld** [comment]
I agree with @simosacchi that the text beside Open Access is unnecessarily cautionary (and adds to the length concern).  I'd be fine with just a link to Sherpa Romeo - but others I suspect want us to explain this caution to users somewhere, thus I suggested a possible help page.  But @heidisb has at least shortened it, which is good!

**Comment by justcolin** [comment]
@projecthydra/sufia-ui-ux-advisors: Would one of you be willing to write a second draft incorporating these recommendations?

**Comment by heidisb** [comment]
I have the md file already, so I do it later today and share.

**Comment by justcolin** [comment]
Thanks @heidisb! I look forward to reading it.

**Comment by simosacchi** [comment]
And I can contribute with feedback in case

**Comment by heidisb** [comment]
Bah...it's only really two changes. Here you go... better, all?

## Help Text 

Who should be able to view or download this content and see the associated metadata? 

##Labels 
**Open Access** - Everyone. Check out [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/) for specific publishers' copyright policies if you plan to patent and/or publish your work in a journal.

**Your Institution** - Only users who are logged in through your institution. 

**Private** - Only users and/or groups that have been given specific access in the "Share With" section.

**Embargo**

**Lease**

**Comment by elrayle** [comment]
Is all this text going in the Save Work widget on the right hand side?

**Comment by heidisb** [comment]
All in page. No more pop-up thing.

**Comment by newmanld** [comment]
+1 to the less discouraging tone beside Open Access.  Thanks @heidisb!

**Comment by simosacchi** [comment]
Thanks for the second draft @heidisb . Any other thought on how to make the "Lease" and "Embargo" options more visually clear/appealing?

**Comment by elrayle** [comment]
@heidisb, thanks for the clarification. Now that there are no more popups, where is the help text for visibility appearing on the page?  Is there a screen shot?  I didn't see the text in @simosacchi's screen shot.

**Comment by simosacchi** [comment]
@elrayle my screenshot is from a local deploy of Sufia master (as of today) so it might not be up to date.

**Comment by heidisb** [comment]
What I posted **is** the text. Just a sentence and then the description of each visibility option right with the radio buttons.

**Comment by elrayle** [comment]
At this point, I am interested in the visual appearance.  Once an update with the new text is complete, can you post a screenshot of the change here?

**Comment by heidisb** [comment]
Totally fair. That'll be @justcolin.

**Comment by justcolin** [comment]
@elrayle: I'll work up a screenshot of what the current interface looks like with these changes as soon as I get out of these meetings.

**Comment by justcolin** [comment]
@elrayle See my initial post at the top of this issue for a screen shot of what CC HEAD currently looks like.

**Comment by elrayle** [comment]
So, I think part of my confusion was that I was thinking about how this looks in Sufia, which (at least in the past) matches @simosacchi's screen shot which has the visibility selection in a Save Work widget on the right hand side of the screen.  I just connected with the fact that your screen shot at the top is coming from CC which has the visibility selection at the bottom of a single page form similar to that used in Sufia 6.x.  Will Sufia 7 also show help text for all data entry items on the New Work form?

**Comment by justcolin** [comment]
@elrayle: Sufia 7 also now always shows the help text. See: projecthydra/sufia#2003. The suggested improvements for CC help text in this issue are also designed to improve the help text in Sufia.

**Comment by justcolin** [comment]
@projecthydra/sufia-ui-ux-advisors: With zero effort the make the styling any better the new content looks like this (I can work on a suggested redesign if people are happy with the copy):

![screen shot 2016-05-27 at 3 52 14 pm](https://cloud.githubusercontent.com/assets/11234702/15619570/11c5a298-2423-11e6-86e4-0fa03fbc158b.png)

**Comment by bnhowell** [comment]
+1 @justcolin. Let's let the spacing breathe a little. Users I tested kept
hitting the visibility tag (open access) thinking it was a button.

On Fri, May 27, 2016 at 3:53 PM, justcolin <notifications@github.com> wrote:

> @projecthydra/sufia-ui-ux-advisors
> <https://github.com/orgs/projecthydra/teams/sufia-ui-ux-advisors>: With
> zero effort the make the styling any better the new content looks like this
> (I can work on a suggested redesign if people are happy with the copy):
>
> [image: screen shot 2016-05-27 at 3 52 14 pm]
> <https://cloud.githubusercontent.com/assets/11234702/15619570/11c5a298-2423-11e6-86e4-0fa03fbc158b.png>
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/projecthydra/curation_concerns/issues/824#issuecomment-222238669>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqv8xYKX9iZ8AiJE3tLJmu3iZoaDK1ks5qF0umgaJpZM4Ioo9D>
> .
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by simosacchi** [comment]
I would change "...publish work in a journal." to something more generic than just "journal". What about "publish your work with a publisher"?

Talking about layout/redesign: is the help text going to stay inline with the labels? 

And yes, please pitch in also on what I suggested in a previous comment on the layout for "Embargo" and "Lease"

**Comment by heidisb** [comment]
Good call @simosacchi. It can totally just be... "patent and/or publish your work." Cut words, friends. And I like your previous suggestion for Embargo/Lease -- current status until when, then what -- in more of a list form. The current setup is wacky and looks like a mad lib.

**Comment by simosacchi** [comment]
@heidisb I thought about having just "patent and/or publish your work."... my only concern with that is the meaning of "publish", as some people consider submission to a IR (or other repo) an act of publication ("make it available to the public"). Therefore I added "publish with a publisher".
