### ISSUE TITLE
Including Google Analytics id in config does not permit application to start.

### ISSUE THREAD

**Issue by grosscol** [projecthydra/curation_concerns#827]
### Descriptive summary

Include what version of CurationConcerns relates to this issue (0.7.x, 0.8.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

```
.../curation_concerns/.internal_test_app/config/initializers/curation_concerns.rb:20:in `block in <top (required)>': undefined method `google_analytics_id=' for #<CurationConcerns::Configuration:0x00560fcd9b0388> (NoMethodError)
	from .../curation_concerns/lib/curation_concerns/configuration.rb:10:in `configure'
	from .../curation_concerns/.internal_test_app/config/initializers/curation_concerns.rb:1:in `<top (required)>'

```

### Expected behavior
Google analytics id to be included in relevant pages via `app/views/shared/_ga.html.erb`

### Actual behavior
Application fails to start

### Steps to reproduce the behavior

1. Generate .internal_test_app
1. Modify `.internal_test_app/config/initializers/curation_concerns.rb` by uncommenting the `google_analytics_id=` line.
3. Run the application `bundle exec rails s`

**Comment by mjgiarlo** [comment]
This feature looks like it's mostly in Sufia. Should it live entirely in Sufia? @tpendragon @escowles @jpstroop @jcoyne

**Comment by tpendragon** [comment]
I'm personally okay taking it out of CC, at least for the moment, since none of the stats dashboard kind of stuff is there right now and adding it to your own application isn't always desired, and even if it is it's an easy thing to do.

**Comment by jpstroop** [comment]
:+1:

**Comment by mjgiarlo** [comment]
:clap:
