### ISSUE TITLE
Is projecthydra/sufia-code-reviewers group working?

### ISSUE THREAD

**Issue by escowles** [projecthydra/curation_concerns#833]
### Descriptive summary

A new PR was just opened by @eliotjordan: #832 

The PR included the @projecthydra/sufia-code-reviewers group but it doesn't look like the group was notified (I didn't get an email AFAICT).

### Expected behavior

Sufia code reviewers should be notified.

### Actual behavior

Not sure if they were or not.

**Comment by escowles** [comment]
Related, as a member of the group, I can see the membership list at https://github.com/orgs/projecthydra/teams/sufia-code-reviewers

But it looks like non-members cannot view the membership (and get a 404).  Should the membership list be public?  Can it?

**Comment by mjgiarlo** [comment]
It's a visible group now. I wonder if it's fixed?

**Comment by jpstroop** [comment]
I can see it.

**Comment by jpstroop** [comment]
and I can ping `@projecthydra/sufia-code-reviewers`. Closing.
