### ISSUE TITLE
Broken javascript, especially in file manager

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/curation_concerns#896]
### Descriptive summary

File uploader and File manager are both broken.

Javascript errors:
![screen shot 2016-08-12 at 11 58 52 am](https://cloud.githubusercontent.com/assets/845363/17628608/34476200-6084-11e6-9a5c-c81262bc2962.png)

Making fileuploader the first require in app/assets/javascripts/curation_concerns/curation_concerns.js resolves the error and fixes the file uploader, but does not fix file manager.

Putting the filemanager requires first creates the following errors:
![screen shot 2016-08-12 at 12 03 42 pm](https://cloud.githubusercontent.com/assets/845363/17628739/dd319700-6084-11e6-941b-5c3a9dedda80.png)

The problem appears to have been introduced in https://github.com/projecthydra/hydra-editor/commit/d38f1e79ae490359a8f3aeac97d162ece3c0eae6#diff-cf46d4dddad62fda63f883d306e44679 because when I pin to its parent the filemanager works and when I pin hydra-editor to that commit it is broken.

The file_manager es6 files are getting wrapped with what I believe @jcoyne says is some almond stuff, but they were already getting prepended with some other stuff I think from babel and it seems that the almond stuff is breaking them. https://gist.github.com/hackmastera/d6d26a85d55cbc938041cc1beac41f85 shows the result I'm getting in my browser.

### Expected behavior
File manager should allow drag/drop of files and works

### Actual behavior
No drag and therefore also no drop.

### Steps to reproduce the behavior

1. Pull master, do a new bundle install and engine cart generation
1. Run the test app. create a work some some files
1. navigate to file manager and attempt to drag something.

### Related work
possibly related to #884?

**Comment by mjgiarlo** [comment]
Pinging @tpendragon about this ticket too.

**Comment by tpendragon** [comment]
@jcoyne I don't know anything about almond - can we just remove it, or should we be converting everything to work with it?

**Comment by tpendragon** [comment]
@hackmastera Thank you so much for the detailed track-down. https://github.com/projecthydra/curation_concerns/compare/file_manager_issues fixes the JS part of the issue, but it looks like there's some ruby problems too that I'll try to track down tomorrow.
