### ISSUE TITLE
file manager drag/drop dead spot

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/curation_concerns#915]
### Descriptive summary

cc1.4

If I have 4 children of a work (in file manager, 1 full row and 1 item on the 2nd row)
I cannot drag the last object into position 3. I also cannot drag the 3rd object into position 4.

**Comment by hackmastera** [comment]
Hey it looks like I can drop 4th object into 3rd position if I hit just the right spot, but the old 3rd position object doesn't move out of the way onto the next row. the next row disappears altogether, actually, after i start dragging the 4th object (footer jumps up). This is in Chrome. going to try ff.

**Comment by tpendragon** [comment]
I'm not sure if this will fix it, but we have something like https://github.com/pulibrary/plum/blob/master/app/assets/javascripts/file_manager/plum.es6#L18-L22 in Plum, I wonder if that would fix it?

**Comment by hackmastera** [comment]
that looks promising let me try to plug it in.
