### ISSUE TITLE
Use title_or_label in search form

### ISSUE THREAD

**Issue by awead** [projecthydra/curation_concerns#933]
### Descriptive summary

Use `title_or_label` here: https://github.com/projecthydra/curation_concerns/blob/master/app/views/collections/_search_form.html.erb#L2

Otherwise, the collection title will appear to the screen reader as `["title"]` and not "title."

**Comment by jcoyne** [comment]
@awead is it possible this is needs fixing in sufia too? https://travis-ci.org/projecthydra/sufia/jobs/156658300#L1896

**Comment by awead** [comment]
@jcoyne either call something else in the form or add `title_or_label` to the form?
