### ISSUE TITLE
Use local_prefixes instead of internal _prefix

### ISSUE THREAD

**Issue by awead** [projecthydra/curation_concerns#939]
### Descriptive summary

We're overriding `_prefixes` in https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/curation_concern_controller.rb#L138

But as of Rails 4.2, there's `local_prefixes which may be a better option.

**Comment by awead** [comment]
As per slack discussion with @tpendragon and @cbeer

**Comment by cbeer** [comment]
We still need to override `_prefixes`; `local_prefixes` gets prepended to the regular prefixes, but we're trying to add some fallbacks instead.
