### ISSUE TITLE
Deprecate and remove SelectsCollections

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/curation_concerns#964]
This module isn't very cohesive and could better be written in fashion similar to https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/admin_set_service.rb

Keep in mind that it's used in Sufia:

https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/my_controller_behavior.rb#L16-L17

**Comment by atz** [comment]
Yeah, I don't like the approach of SelectsCollections (or the similar modules).  

I could wrap this into what I'm doing with `CollectionSearchBuilder` anyway.

**Comment by atz** [comment]
SelectsCollections link for the lazy: https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/selects_collections.rb

**Comment by atz** [comment]
How long would the deprecation period last?

**Comment by jcoyne** [comment]
@atz I set the deprecation horizion as 2.0 in the PR.

**Comment by atz** [comment]
OK, can you hold off on that until larger PR is in?
https://github.com/projecthydra/curation_concerns/pull/968

I think the availability of access-aware CollectionSearchController basically makes SelectsCollections unnecessary, and it would be nice to mention that in the deprecations.
